site_name: Hexalith Documentation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - About: about.md  
theme: readthedocs